import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'preview_assets.g.dart';

/// The Flutter-web preview embedded in the CLI binary (generated by
/// `tool/embed_preview.dart`). Lets `krom dev` serve the preview from a
/// distributed `krom` without a separate `make deploy-preview`.
///
/// Files are stored gzip-compressed + base64 and decoded lazily on first read.
/// CanvasKit is fetched from the gstatic CDN at runtime, so it is not embedded —
/// the preview needs network access for the renderer (a dev-machine assumption).
class EmbeddedPreview {
  EmbeddedPreview._();

  static final Map<String, Uint8List> _decoded = {};

  /// Whether a preview was embedded at build time. False when the generated
  /// assets are the empty placeholder (e.g. a source checkout that never ran the
  /// generator) — callers then fall back to the "build the preview" page.
  static bool get isAvailable => kEmbeddedPreviewGz.isNotEmpty;

  /// The `.last_build_id` of the embedded preview, for diagnostics.
  static String get buildId => kEmbeddedPreviewBuildId;

  /// Decoded bytes for [path] (e.g. `index.html`, `main.dart.js`,
  /// `assets/fonts/MaterialIcons-Regular.otf`), or null if not embedded.
  /// A leading `/` and the empty path (→ `index.html`) are normalised.
  static Uint8List? read(String path) {
    final key = _normalize(path);
    final cached = _decoded[key];
    if (cached != null) return cached;

    final b64 = kEmbeddedPreviewGz[key];
    if (b64 == null) return null;

    final bytes = Uint8List.fromList(gzip.decode(base64.decode(b64)));
    _decoded[key] = bytes;
    return bytes;
  }

  static String _normalize(String path) {
    var key = path;
    if (key.startsWith('/')) key = key.substring(1);
    if (key.isEmpty) key = 'index.html';
    return key;
  }
}
